import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './Navbar';
import AuthProvider from './api/auth/Provider';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main className="p-5">
            <Image
              src="https://bit.ly/react-cover"
              width={300}
              height={150}
              quality={100}
              alt="react cover"
            />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
